[package]
name = "custom-slice"
version = "0.1.0"
edition = "2021"

[features]

# default = ["std"]

std = ["alloc"]
alloc = []

[dependencies]
thin-ptr = { git = "https://github.com/RustyYato/thin-ptr.git", branch = "main" }
